### ISSUE TITLE
Tree Fracture

### ISSUE THREAD

**Issue by jonassorgenfrei** [joshuazt/JZTREES#1]
Heyhey, 
first i wanna say the tool is really awesome and thanks for sharing it with the community. 

I just found two small problems.  The output2 in the JZT_TreeFracture hda is connected to OutputIndex 3 instead of 2. 
As well as having some problems with the demo scene and the JZT_TreeFracture in H19.

**Comment by joshuazt** [comment]
hey Joans, thanks for reporting this. I just fixed that output index will upload a fix shortly. That output was just to see an exploded view of the fractured tree. 

Can I get some more detail about what is going on with the gumtree demo scene? On my end its still all working

**Comment by jonassorgenfrei** [comment]
Hey joshua thanks for your fast responds.
When I'm trying to create a TreeFracture Node in H19 (windows 383&437) I get the follwoing error: 
There were errors while matching the new new to its definitions:


Error:       Unknown operator on load "JZT_TreeFracture2/rbdconfigure1/selection".
             Unknown operator on load "JZT_TreeFracture2/rbdconfigure1/selection".
             Unknown operator on load "JZT_TreeFracture2/rbdconfigure1/selection".
             Unknown operator on load "JZT_TreeFracture2/rbdconfigure1/selection".
             Unknown operator on load "JZT_TreeFracture2/rbdconfigure1/selection/input".
             Unknown operator on load "JZT_TreeFracture2/rbdconfigure1/selection/input".
             Unknown operator on load "JZT_TreeFracture2/rbdconfigure1/selection/input".
             Unknown operator on load "JZT_TreeFracture2/rbdconfigure1/selection/selection".
             Unknown operator on load "JZT_TreeFracture2/rbdconfigure1/selection/selection".
             Unknown operator on load "JZT_TreeFracture2/rbdconfigure1/selection/selection".
             Unknown operator on load "JZT_TreeFracture2/rbdconfigure1/selection".
             Unknown operator on load "JZT_TreeFracture2/rbdconfigure1/selection".
             
It creates the HDA but as opened HDA.

**Comment by joshuazt** [comment]
sounds like a houdini 19 issue, having a look shortly. I haven't switched h19 yet.

**Comment by jonassorgenfrei** [comment]
Yeah it seems like they changed some stuff on the rbd configure node. 
Cool i switched back to h18 for the rbd sim. But man great tool and awesome workflow love playing around with it.

**Comment by joshuazt** [comment]
yeah they did, I'm going to look at embedding the interal HDA's after work today. Thanks for flagging this!

Thanks, Jonas :) checkout the roadmap on Trello btw, I've added this bug to the list: 

https://trello.com/b/bKcqHstM/jztrees-development-roadmap

**Comment by jonassorgenfrei** [comment]
Awesome great :) And Thanks for the fast help :)

**Comment by joshuazt** [comment]
Hey, Just a little update for anyone wondering. H19 support will be coming this weekend. I finally upgraded my system to H19 and will do testing this weekend.
