### ISSUE TITLE
Fern example is broken?

### ISSUE THREAD

**Issue by akdbra** [joshuazt/JZTREES#2]
Hey!
Thanks for sharing this awesome toolkit.
Trying to dig in to it but it seems that Fern examples is broken.
Or more specific is gen type opposite
![image](https://user-images.githubusercontent.com/94026/157435459-7d2eb62d-db1e-4a72-8986-ed271415e485.png)

**Comment by joshuazt** [comment]
@sick ah yep, thankyou for letting me know. I have just released a hotfix. I deleted an important piece of vex late one night... 
![image](https://user-images.githubusercontent.com/23189306/157555564-23d40bf6-e973-4dbc-956d-14263b486cd9.png)

**Comment by akdbra** [comment]
Awesome, thanks.
